name: CI to Docker Hub

on:
  push:
    branches: [ main, add-docker-prod ]
  
  jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Buid and push
          id: docker_build
          uses: docker/build-push-actions@v6
          with:
            context: ./
            file: ./docker/prod/Dockerfile
            push: true
            tags: captainkaeru/ruby-getting-started-app-prod:latest

        - name: Image Digest
          run: echo ${{ steps.docker_build.outputs.digest }}

